//
//  CoreImageFilterEnumeration.h
//  CoreImageFilterEnumeration
//
//  Created by Joshua Sullivan on 10/10/14.
//  Copyright (c) 2014 Joshua Sullivan. All rights reserved.
//

#import <CoreImageFilterEnumeration/CIEAccordionFoldTransition.h>
#import <CoreImageFilterEnumeration/CIEAdditionCompositing.h>
#import <CoreImageFilterEnumeration/CIEAffineClamp.h>
#import <CoreImageFilterEnumeration/CIEAffineTile.h>
#import <CoreImageFilterEnumeration/CIEAffineTransform.h>
#import <CoreImageFilterEnumeration/CIEAreaHistogram.h>
#import <CoreImageFilterEnumeration/CIEAztecCodeGenerator.h>
#import <CoreImageFilterEnumeration/CIEBarsSwipeTransition.h>
#import <CoreImageFilterEnumeration/CIEBlendWithAlphaMask.h>
#import <CoreImageFilterEnumeration/CIEBlendWithMask.h>
#import <CoreImageFilterEnumeration/CIEBloom.h>
#import <CoreImageFilterEnumeration/CIEBumpDistortion.h>
#import <CoreImageFilterEnumeration/CIEBumpDistortionLinear.h>
#import <CoreImageFilterEnumeration/CIECheckerboardGenerator.h>
#import <CoreImageFilterEnumeration/CIECircleSplashDistortion.h>
#import <CoreImageFilterEnumeration/CIECircularScreen.h>
#import <CoreImageFilterEnumeration/CIECode128BarcodeGenerator.h>
#import <CoreImageFilterEnumeration/CIEColorBlendMode.h>
#import <CoreImageFilterEnumeration/CIEColorBurnBlendMode.h>
#import <CoreImageFilterEnumeration/CIEColorClamp.h>
#import <CoreImageFilterEnumeration/CIEColorControls.h>
#import <CoreImageFilterEnumeration/CIEColorCrossPolynomial.h>
#import <CoreImageFilterEnumeration/CIEColorCube.h>
#import <CoreImageFilterEnumeration/CIEColorCubeWithColorSpace.h>
#import <CoreImageFilterEnumeration/CIEColorDodgeBlendMode.h>
#import <CoreImageFilterEnumeration/CIEColorInvert.h>
#import <CoreImageFilterEnumeration/CIEColorMap.h>
#import <CoreImageFilterEnumeration/CIEColorMatrix.h>
#import <CoreImageFilterEnumeration/CIEColorMonochrome.h>
#import <CoreImageFilterEnumeration/CIEColorPolynomial.h>
#import <CoreImageFilterEnumeration/CIEColorPosterize.h>
#import <CoreImageFilterEnumeration/CIEConstantColorGenerator.h>
#import <CoreImageFilterEnumeration/CIEConvolution3X3.h>
#import <CoreImageFilterEnumeration/CIEConvolution5X5.h>
#import <CoreImageFilterEnumeration/CIEConvolution9Horizontal.h>
#import <CoreImageFilterEnumeration/CIEConvolution9Vertical.h>
#import <CoreImageFilterEnumeration/CIECopyMachineTransition.h>
#import <CoreImageFilterEnumeration/CIECrop.h>
#import <CoreImageFilterEnumeration/CIEDarkenBlendMode.h>
#import <CoreImageFilterEnumeration/CIEDifferenceBlendMode.h>
#import <CoreImageFilterEnumeration/CIEDisintegrateWithMaskTransition.h>
#import <CoreImageFilterEnumeration/CIEDissolveTransition.h>
#import <CoreImageFilterEnumeration/CIEDivideBlendMode.h>
#import <CoreImageFilterEnumeration/CIEDotScreen.h>
#import <CoreImageFilterEnumeration/CIEEightfoldReflectedTile.h>
#import <CoreImageFilterEnumeration/CIEExclusionBlendMode.h>
#import <CoreImageFilterEnumeration/CIEExposureAdjust.h>
#import <CoreImageFilterEnumeration/CIEFalseColor.h>
#import <CoreImageFilterEnumeration/CIEFlashTransition.h>
#import <CoreImageFilterEnumeration/CIEFourfoldReflectedTile.h>
#import <CoreImageFilterEnumeration/CIEFourfoldRotatedTile.h>
#import <CoreImageFilterEnumeration/CIEFourfoldTranslatedTile.h>
#import <CoreImageFilterEnumeration/CIEGammaAdjust.h>
#import <CoreImageFilterEnumeration/CIEGaussianBlur.h>
#import <CoreImageFilterEnumeration/CIEGaussianGradient.h>
#import <CoreImageFilterEnumeration/CIEGlassDistortion.h>
#import <CoreImageFilterEnumeration/CIEGlideReflectedTile.h>
#import <CoreImageFilterEnumeration/CIEGloom.h>
#import <CoreImageFilterEnumeration/CIEHardLightBlendMode.h>
#import <CoreImageFilterEnumeration/CIEHatchedScreen.h>
#import <CoreImageFilterEnumeration/CIEHighlightShadowAdjust.h>
#import <CoreImageFilterEnumeration/CIEHistogramDisplayFilter.h>
#import <CoreImageFilterEnumeration/CIEHoleDistortion.h>
#import <CoreImageFilterEnumeration/CIEHueAdjust.h>
#import <CoreImageFilterEnumeration/CIEHueBlendMode.h>
#import <CoreImageFilterEnumeration/CIELanczosScaleTransform.h>
#import <CoreImageFilterEnumeration/CIELightenBlendMode.h>
#import <CoreImageFilterEnumeration/CIELightTunnel.h>
#import <CoreImageFilterEnumeration/CIELinearBurnBlendMode.h>
#import <CoreImageFilterEnumeration/CIELinearDodgeBlendMode.h>
#import <CoreImageFilterEnumeration/CIELinearGradient.h>
#import <CoreImageFilterEnumeration/CIELinearToSRGBToneCurve.h>
#import <CoreImageFilterEnumeration/CIELineScreen.h>
#import <CoreImageFilterEnumeration/CIELuminosityBlendMode.h>
#import <CoreImageFilterEnumeration/CIEMaskToAlpha.h>
#import <CoreImageFilterEnumeration/CIEMaximumComponent.h>
#import <CoreImageFilterEnumeration/CIEMaximumCompositing.h>
#import <CoreImageFilterEnumeration/CIEMinimumComponent.h>
#import <CoreImageFilterEnumeration/CIEMinimumCompositing.h>
#import <CoreImageFilterEnumeration/CIEModTransition.h>
#import <CoreImageFilterEnumeration/CIEMultiplyBlendMode.h>
#import <CoreImageFilterEnumeration/CIEMultiplyCompositing.h>
#import <CoreImageFilterEnumeration/CIEOverlayBlendMode.h>
#import <CoreImageFilterEnumeration/CIEPerspectiveCorrection.h>
#import <CoreImageFilterEnumeration/CIEPerspectiveTile.h>
#import <CoreImageFilterEnumeration/CIEPerspectiveTransform.h>
#import <CoreImageFilterEnumeration/CIEPerspectiveTransformWithExtent.h>
#import <CoreImageFilterEnumeration/CIEPhotoEffectChrome.h>
#import <CoreImageFilterEnumeration/CIEPhotoEffectFade.h>
#import <CoreImageFilterEnumeration/CIEPhotoEffectInstant.h>
#import <CoreImageFilterEnumeration/CIEPhotoEffectMono.h>
#import <CoreImageFilterEnumeration/CIEPhotoEffectNoir.h>
#import <CoreImageFilterEnumeration/CIEPhotoEffectProcess.h>
#import <CoreImageFilterEnumeration/CIEPhotoEffectTonal.h>
#import <CoreImageFilterEnumeration/CIEPhotoEffectTransfer.h>
#import <CoreImageFilterEnumeration/CIEPinchDistortion.h>
#import <CoreImageFilterEnumeration/CIEPinLightBlendMode.h>
#import <CoreImageFilterEnumeration/CIEPixellate.h>
#import <CoreImageFilterEnumeration/CIEQRCodeGenerator.h>
#import <CoreImageFilterEnumeration/CIERadialGradient.h>
#import <CoreImageFilterEnumeration/CIERandomGenerator.h>
#import <CoreImageFilterEnumeration/CIESaturationBlendMode.h>
#import <CoreImageFilterEnumeration/CIEScreenBlendMode.h>
#import <CoreImageFilterEnumeration/CIESepiaTone.h>
#import <CoreImageFilterEnumeration/CIESharpenLuminance.h>
#import <CoreImageFilterEnumeration/CIESixfoldReflectedTile.h>
#import <CoreImageFilterEnumeration/CIESixfoldRotatedTile.h>
#import <CoreImageFilterEnumeration/CIESmoothLinearGradient.h>
#import <CoreImageFilterEnumeration/CIESoftLightBlendMode.h>
#import <CoreImageFilterEnumeration/CIESourceAtopCompositing.h>
#import <CoreImageFilterEnumeration/CIESourceInCompositing.h>
#import <CoreImageFilterEnumeration/CIESourceOutCompositing.h>
#import <CoreImageFilterEnumeration/CIESourceOverCompositing.h>
#import <CoreImageFilterEnumeration/CIESRGBToneCurveToLinear.h>
#import <CoreImageFilterEnumeration/CIEStarShineGenerator.h>
#import <CoreImageFilterEnumeration/CIEStraightenFilter.h>
#import <CoreImageFilterEnumeration/CIEStripesGenerator.h>
#import <CoreImageFilterEnumeration/CIESubtractBlendMode.h>
#import <CoreImageFilterEnumeration/CIESwipeTransition.h>
#import <CoreImageFilterEnumeration/CIETemperatureAndTint.h>
#import <CoreImageFilterEnumeration/CIEToneCurve.h>
#import <CoreImageFilterEnumeration/CIETriangleKaleidoscope.h>
#import <CoreImageFilterEnumeration/CIETwelvefoldReflectedTile.h>
#import <CoreImageFilterEnumeration/CIETwirlDistortion.h>
#import <CoreImageFilterEnumeration/CIEUnsharpMask.h>
#import <CoreImageFilterEnumeration/CIEVibrance.h>
#import <CoreImageFilterEnumeration/CIEVignette.h>
#import <CoreImageFilterEnumeration/CIEVignetteEffect.h>
#import <CoreImageFilterEnumeration/CIEVortexDistortion.h>
#import <CoreImageFilterEnumeration/CIEWhitePointAdjust.h>
